# Algèbre linéaire : Factorisations 

In [34]:
import numpy as np
from display import display_matrix_lateX, display_matrix_pyplot

##  I. Factorisation LU

In [110]:
def factorisation_lu(A):
    L1 = np.diag(np.ones((A.shape[0])))
    for id_act, line_act in enumerate(A):
        print("current:", line_act)
        if A[id_act, id_act] == 0:
            return
        diag_elem = A[id_act, id_act]
        for ind, line in enumerate(A[id_act+1:]):
            real_id = ind+id_act+1
            temp_elem = A[real_id, id_act]
            factor = temp_elem/diag_elem
            A[real_id] = A[id_act] - factor * A[real_id]
            L1[real_id, id_act] += factor
            print(line)
        print("next")
    return L1

In [111]:
# quelques exemples de matrices pour tester

I_3 = np.diag([1, 1, 1])
A_1 = np.array([[2,0,2,0],[-2,1,-2,1],[2,-1,5,0],[-2,1,-5,-1]])
L_1 = np.array([[1, 0, 0, 0], [-1, 1, 0, 0], [1, -1, 1, 0], [-1, 1, -1, 1]])
U_1 = np.array([[2, 0, 2, 0], [0, 1, 0, 1], [0, 0, 3, 1], [0, 0, 0, -1]])

In [112]:
factorisation_lu(A_1)

current: [2 0 2 0]
[0 1 0 1]
[ 0  1 -3  0]
[ 0  1 -3 -1]
next
current: [0 1 0 1]
[0 0 3 1]
[0 0 3 2]
next
current: [0 0 3 1]
[ 0  0  0 -1]
next
current: [ 0  0  0 -1]
next


array([[ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [-1., -1.,  1.,  0.],
       [ 1., -1., -1.,  1.]])